version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisData:/data
  mongo:
    image: "mongo:3.4"
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
      - ~/dump:/dump
    command: mongod --auth
  # app:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #     - nodeModules:/app/node_modules
  #     - logData:/app/log
  #   ports:
  #     - "4040:4040"
  #     - "9229:9229"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - mongo
  #     - redis
  #   command: pm2 start --name "crictecScoring" --no-daemon npm -- run start
volumes:
  logData:
  mongoData:
  redisData:
  nodeModules:
