version: '2'

services:
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redisData: /data
  mongo:
    image: "mongo:3.4"
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sw33tM0ng0
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
      - ~/dump:/dump
    command: mongod --auth
  app:
    image: "172.31.19.46:5000/scoring:0.0.3"
    container_name: scoring
    environment:
      - NODE_ENV=production
    volumes:
      - logData:/app/log
    depends_on:
      - mongo
      # - redis
    command: pm2 start --name "crictecScoring" --no-daemon server.js

    # Expose ports [HOST:CONTAINER}
    ports:
      - "4040:4040"
volumes:
  logData:
  mongoData:
  # redisData:
